"""Core analytics used by the Streamlit dashboard."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import timedelta
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd

ALERT_LEVELS = ["OK", "Informativa", "Media", "Crítica"]

TEMPERATURE_THRESHOLDS = {
    "Informativa": (26.0, 27.9),
    "Media": (28.0, 29.4),
    "Crítica": (29.5, None),
}

HUMIDITY_THRESHOLDS = {
    "Informativa": (70.0, 75.0),
    "Media": (75.0, 80.0),
    "Crítica": (80.0, None),
}

ENERGY_THRESHOLDS = {
    "Informativa": (18.0, 22.0),
    "Media": (22.0, 26.0),
    "Crítica": (26.0, None),
}


@dataclass
class Forecast:
    """Forecast result for a single variable."""

    piso: int
    variable: str
    forecast_timestamp: pd.Timestamp
    value: float
    model: str


@dataclass
class Alert:
    """Alert generated by the analytics engine."""

    timestamp: pd.Timestamp
    piso: int
    variable: str
    nivel: str
    mensaje: str
    tipo: str


def _fit_linear_forecast(series: pd.Series, horizon: int) -> float:
    """Fit a simple linear trend and project *horizon* minutes ahead."""

    if len(series) < 3:
        return float(series.iloc[-1])

    x = np.arange(len(series))
    y = series.to_numpy(dtype=float)
    coeffs = np.polyfit(x, y, 1)
    slope, intercept = coeffs
    return float(slope * (len(series) - 1 + horizon) + intercept)


def generate_forecasts(
    df: pd.DataFrame,
    horizon_minutes: int = 60,
    window_minutes: int = 120,
) -> List[Forecast]:
    """Generate per-floor forecasts for temperature, humidity and energy."""

    forecasts: List[Forecast] = []
    latest_time = df["timestamp"].max()
    forecast_time = latest_time + timedelta(minutes=horizon_minutes)
    window = timedelta(minutes=window_minutes)

    for piso, group in df.groupby("piso"):
        floor_window = group[group["timestamp"] >= latest_time - window]
        if floor_window.empty:
            continue
        for variable, column in (
            ("temperatura", "temp_c"),
            ("humedad", "humedad_pct"),
            ("energia", "energia_kw"),
        ):
            value = _fit_linear_forecast(floor_window[column], horizon_minutes)
            forecasts.append(
                Forecast(
                    piso=int(piso),
                    variable=variable,
                    forecast_timestamp=forecast_time,
                    value=value,
                    model="tendencia lineal",
                )
            )
    return forecasts


def _evaluate_threshold(value: float, thresholds: Dict[str, Tuple[float, float | None]]) -> str:
    for level in ("Crítica", "Media", "Informativa"):
        lower, upper = thresholds[level]
        if upper is None and value >= lower:
            return level
        if lower is None and value <= upper:  # currently unused but kept for completeness
            return level
        if lower is not None and upper is not None and lower <= value <= upper:
            return level
    return "OK"


def _compose_alert(variable: str, level: str, piso: int, value: float) -> str:
    if variable == "temperatura":
        if level == "Crítica":
            return f"Piso {piso}: temperatura proyectada de {value:.1f} °C excede el umbral crítico."
        if level == "Media":
            return f"Piso {piso}: temperatura elevada ({value:.1f} °C), ajustar HVAC."
        if level == "Informativa":
            return f"Piso {piso}: temperatura subiendo a {value:.1f} °C, monitorear."
    if variable == "humedad":
        if level == "Crítica":
            return f"Piso {piso}: humedad {value:.1f}% requiere acción inmediata."
        if level == "Media":
            return f"Piso {piso}: humedad fuera de rango ({value:.1f}%)."
        if level == "Informativa":
            return f"Piso {piso}: humedad acercándose a límites ({value:.1f}%)."
    if variable == "energia":
        if level == "Crítica":
            return f"Piso {piso}: consumo {value:.1f} kW es crítico."
        if level == "Media":
            return f"Piso {piso}: consumo elevado ({value:.1f} kW)."
        if level == "Informativa":
            return f"Piso {piso}: consumo creciente ({value:.1f} kW)."
    return f"Piso {piso}: {variable} en {value:.1f}."


def detect_alerts(
    df: pd.DataFrame,
    forecasts: Iterable[Forecast],
    min_delta_temp: float = 2.5,
) -> List[Alert]:
    """Detect threshold and predictive alerts."""

    alerts: List[Alert] = []
    latest = df.groupby("piso").tail(1)
    latest = latest.set_index("piso")

    for piso, row in latest.iterrows():
        temp_level = _evaluate_threshold(row["temp_c"], TEMPERATURE_THRESHOLDS)
        if temp_level != "OK":
            alerts.append(
                Alert(
                    timestamp=row["timestamp"],
                    piso=int(piso),
                    variable="temperatura",
                    nivel=temp_level,
                    mensaje=_compose_alert("temperatura", temp_level, piso, row["temp_c"]),
                    tipo="Actual",
                )
            )

        hum_level = _evaluate_threshold(row["humedad_pct"], HUMIDITY_THRESHOLDS)
        if hum_level != "OK":
            alerts.append(
                Alert(
                    timestamp=row["timestamp"],
                    piso=int(piso),
                    variable="humedad",
                    nivel=hum_level,
                    mensaje=_compose_alert("humedad", hum_level, piso, row["humedad_pct"]),
                    tipo="Actual",
                )
            )

        energy_level = _evaluate_threshold(row["energia_kw"], ENERGY_THRESHOLDS)
        if energy_level != "OK":
            alerts.append(
                Alert(
                    timestamp=row["timestamp"],
                    piso=int(piso),
                    variable="energia",
                    nivel=energy_level,
                    mensaje=_compose_alert("energia", energy_level, piso, row["energia_kw"]),
                    tipo="Actual",
                )
            )

        history = df[df["piso"] == piso].tail(2)
        if len(history) == 2:
            delta = history.iloc[1]["temp_c"] - history.iloc[0]["temp_c"]
            if delta >= min_delta_temp:
                alerts.append(
                    Alert(
                        timestamp=row["timestamp"],
                        piso=int(piso),
                        variable="temperatura",
                        nivel="Media",
                        mensaje=f"Piso {piso}: aumento repentino de temperatura (+{delta:.1f} °C).",
                        tipo="Tendencia",
                    )
                )

    for forecast in forecasts:
        if forecast.variable == "temperatura":
            level = _evaluate_threshold(forecast.value, TEMPERATURE_THRESHOLDS)
        elif forecast.variable == "humedad":
            level = _evaluate_threshold(forecast.value, HUMIDITY_THRESHOLDS)
        else:
            level = _evaluate_threshold(forecast.value, ENERGY_THRESHOLDS)

        if level in {"Media", "Crítica"}:
            alerts.append(
                Alert(
                    timestamp=forecast.forecast_timestamp,
                    piso=forecast.piso,
                    variable=forecast.variable,
                    nivel=level,
                    mensaje=_compose_alert(forecast.variable, level, forecast.piso, forecast.value),
                    tipo="Predictiva",
                )
            )
    return alerts


__all__ = [
    "Forecast",
    "Alert",
    "generate_forecasts",
    "detect_alerts",
    "ALERT_LEVELS",
]
